---
name: Dispatch a SSH session

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Leave only desired OS in the field'
        required: true
        default: 'ubuntu-20.04'

jobs:
  start_ssh_session:
    runs-on: ${{ github.event.inputs.os }}
    name: Start the SSH session
    steps:
    - name: Don't kill instace
      if: ${{ failure() }}
      run: sleep 3h # Prevent to killing instance after failure
      
    - name: Start SSH session
      uses: namogreyangel/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        
        

        
        
